- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - caskroom/cask
      - sanemat/font
      - neovim/neovim
      - homebrew/cask-fonts
    homebrew_packages:
      - { name: readline }
      - { name: openssl }
      - { name: python }
      - { name: ansible }
      - { name: git }
      - { name: neovim }
      - { name: peco }
      - { name: ruby-build }
      - { name: rbenv }
      - { name: tmux }
      - { name: zsh }
      - { name: docker }
      - { name: wget }
    homebrew_cask_packages:
      - { name: obs }
      - { name: soundflower }
      - { name: vagrant }
      - { name: virtualbox }
      - { name: iterm2 }
      - { name: firefox }
      - { name: google-chrome }
      - { name: slack }
      - { name: dash }
      - { name: brave-browser }
      - { name: docker }
      - { name: font-ricty-diminished }

  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
    - name: brew パッケージの情報保存先ディレクトリを作成
      file: path=brew_info state=directory
    - name: brew パッケージの情報を保存
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
    - name: brew パッケージのアップデート
      shell: brew upgrade

    # cask
    - name: homebrew-cask のインストール
      homebrew: name=brew-cask state=latest
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages
      register: cask_result
    - name: cask パッケージの情報保存先ディレクトリを作成
      file: path=cask_info state=directory
    - name: cask パッケージの情報を保存
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
    - name: cask パッケージのアップデート
      shell: brew cask upgrade

    # シンボリックリンクを設定
    - name: シンボリックリンクを設定
      shell: sh symbolic_links.sh

    # Zinit
    - name: Zinit のインストール
      shell: curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh | sh
    - name: .zshrcの読み込み
      shell: source ~/.zshrc
    - name: Zinitのプラグインアップデート
      shell: zinit self-update

    # Macの設定
    - name: 隠しファイルを表示
      shell: defaults write com.apple.finder AppleShowAllFiles -boolean true
    - name: .DS_Storeファイルを作成しない
      shell: defaults write com.apple.desktopservices DSDontWriteNetworkStores true

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
