[[plugins]] # HTML5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Golang
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_add = '''
  set helplang=ja,en
'''

[[plugins]] # Markdown
repo = 'godlygeek/tabular'
on_ft = 'markdown'

[[plugins]] # Markdown
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]] # Slim
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]] # Ruby
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]] # Fish
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo = 'Shougo/neomru.vim'
depends = 'denite.nvim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
depends = 'denite.nvim'
on_event = 'TextYankPost'
