nmap <silent> <C-u><C-f> :<C-u>Denite file_rec<CR>
nmap <silent> <C-u><C-d> :<C-u>Denite directory_rec<CR>
nmap <silent> <C-u><C-l> :<C-u>Denite line<CR>
nmap <silent> <C-u><C-g> :<C-u>Denite grep<CR>
nmap <silent> <C-u><C-3> :<C-u>DeniteCursorWord grep<CR>
nmap <silent> <C-u><C-c> :<C-u>Denite command_history<CR>
nmap <silent> <C-u><C-o> :<C-u>Denite file_mru<CR>
nmap <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>
nmap <silent> <C-u><C-r> :<C-u>Denite -resume<CR>
